service: stale-mr-reminder

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1  # Mumbai region for IST timezone
  timeout: 300  # 5 minutes timeout
  memorySize: 256  # MB
  
  # Environment variables (override these per deployment)
  environment:
    GITLAB_URL: ${env:GITLAB_URL, 'https://gitlab.com'}
    GITLAB_TOKEN: ${env:GITLAB_TOKEN, ''}
    GITLAB_PROJECT_ID: ${env:GITLAB_PROJECT_ID, ''}
    GITLAB_PROJECT_NAME: ${env:GITLAB_PROJECT_NAME, ''}
    GITLAB_PROJECTS: ${env:GITLAB_PROJECTS}
    JIRA_URL: ${env:JIRA_URL}
    JIRA_USERNAME: ${env:JIRA_USERNAME}
    JIRA_TOKEN: ${env:JIRA_TOKEN}
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    STALE_DAYS_THRESHOLD: ${env:STALE_DAYS_THRESHOLD, '2'}
    USE_PRIORITY_THRESHOLDS: ${env:USE_PRIORITY_THRESHOLDS, 'true'}
    THRESHOLD_HIGHEST: ${env:THRESHOLD_HIGHEST, '1'}
    THRESHOLD_HIGH: ${env:THRESHOLD_HIGH, '2'}
    THRESHOLD_MEDIUM: ${env:THRESHOLD_MEDIUM, '3'}
    THRESHOLD_LOW: ${env:THRESHOLD_LOW, '3'}
    THRESHOLD_LOWEST: ${env:THRESHOLD_LOWEST, '3'}
    EXCLUDE_BOTS: ${env:EXCLUDE_BOTS, 'true'}
    EXCLUDE_DEPENDENCIES: ${env:EXCLUDE_DEPENDENCIES, 'true'}
    CUSTOM_BOT_KEYWORDS: ${env:CUSTOM_BOT_KEYWORDS, ''}
    CUSTOM_DEPENDENCY_KEYWORDS: ${env:CUSTOM_DEPENDENCY_KEYWORDS, ''}

  # IAM permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*

functions:
  staleMrReminder:
    handler: lambda_function.lambda_handler
    description: "Daily reminder for stale merge requests"
    events:
      # Run every day at 4:30 PM IST (11:00 AM UTC)
      - schedule: 
          rate: cron(00 11 * * ? *)
          description: "Daily execution at 4:30 PM IST"
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
