service: stale-mr-reminder

provider:
  name: aws
  runtime: python3.9
  region: ap-south-1  # Mumbai region for IST timezone
  timeout: 300  # 5 minutes timeout
  memorySize: 256  # MB
  
  # Environment variables (only global config, all team/project/slack config is in projects_config.yaml)
  environment:
    GITLAB_URL: ${env:GITLAB_URL, 'https://gitlab.com'}
    JIRA_URL: ${env:JIRA_URL}
    JIRA_USERNAME: ${env:JIRA_USERNAME}
    JIRA_TOKEN: ${env:JIRA_TOKEN}
    # All team/project/slack config is now in projects_config.yaml

  # IAM permissions
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: arn:aws:logs:*:*:*

functions:
  staleMrReminder:
    handler: lambda_function.lambda_handler
    description: "Daily reminder for stale merge requests"
    package:
      include:
        - projects_config.yaml  # Ensure this is included in the deployment package
    events:
      # Run every day at 4:30 PM IST (11:00 AM UTC)
      - schedule: 
          rate: cron(00 11 * * ? *)
          description: "Daily execution at 4:30 PM IST"
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false

# Onboarding new teams: just edit projects_config.yaml and redeploy!
