AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stale MR Reminder Lambda Function (Multi-Team YAML Config)

Parameters:
  JiraUrl:
    Type: String
    Description: JIRA Base URL
  JiraUsername:
    Type: String
    Description: JIRA Username
  JiraToken:
    Type: String
    NoEcho: true
    Description: JIRA API Token

Resources:
  StaleMrReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stale-mr-reminder
      CodeUri: ./  # Includes all files in the root directory, including projects_config.yaml
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Description: Daily reminder for stale merge requests
      Environment:
        Variables:
          JIRA_URL: !Ref JiraUrl
          JIRA_USERNAME: !Ref JiraUsername
          JIRA_TOKEN: !Ref JiraToken
          # All team/project/slack config is now in projects_config.yaml
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 11 * * ? *)  # 5 PM IST daily
            Description: Daily execution at 5 PM IST
            Enabled: true
      # Onboarding new teams: just edit projects_config.yaml and redeploy!

  StaleMrReminderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StaleMrReminderFunction}'
      RetentionInDays: 7

Outputs:
  StaleMrReminderFunction:
    Description: Stale MR Reminder Lambda Function ARN
    Value: !GetAtt StaleMrReminderFunction.Arn
  StaleMrReminderFunctionName:
    Description: Stale MR Reminder Lambda Function Name
    Value: !Ref StaleMrReminderFunction
