AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stale MR Reminder Lambda Function

Parameters:
  GitLabToken:
    Type: String
    NoEcho: true
    Description: GitLab Personal Access Token
  GitLabProjectId:
    Type: String
    Description: GitLab Project ID
  JiraUrl:
    Type: String
    Description: JIRA Base URL
  JiraUsername:
    Type: String
    Description: JIRA Username
  JiraToken:
    Type: String
    NoEcho: true
    Description: JIRA API Token
  SlackWebhookUrl:
    Type: String
    NoEcho: true
    Description: Slack Webhook URL

Resources:
  StaleMrReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stale-mr-reminder
      CodeUri: ./
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 300
      MemorySize: 256
      Description: Daily reminder for stale merge requests
      Environment:
        Variables:
          GITLAB_TOKEN: !Ref GitLabToken
          GITLAB_PROJECT_ID: !Ref GitLabProjectId
          JIRA_URL: !Ref JiraUrl
          JIRA_USERNAME: !Ref JiraUsername
          JIRA_TOKEN: !Ref JiraToken
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
          STALE_DAYS_THRESHOLD: '2'
          USE_PRIORITY_THRESHOLDS: 'true'
          THRESHOLD_HIGHEST: '1'
          THRESHOLD_HIGH: '2'
          THRESHOLD_MEDIUM: '3'
          THRESHOLD_LOW: '3'
          THRESHOLD_LOWEST: '3'
          EXCLUDE_BOTS: 'true'
          EXCLUDE_DEPENDENCIES: 'true'
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(30 11 * * ? *)  # 5 PM IST daily
            Description: Daily execution at 5 PM IST
            Enabled: true

  StaleMrReminderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${StaleMrReminderFunction}'
      RetentionInDays: 7

Outputs:
  StaleMrReminderFunction:
    Description: Stale MR Reminder Lambda Function ARN
    Value: !GetAtt StaleMrReminderFunction.Arn
  StaleMrReminderFunctionName:
    Description: Stale MR Reminder Lambda Function Name
    Value: !Ref StaleMrReminderFunction
